name: update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ scoop-package-released ]

jobs:

  smoke-test:
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
      - run: python update-packages.py
        shell: bash

      - name: Create PR for version update
        id: create-pr
        shell: bash
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git config pull.ff only
          git checkout -b deps_update
          git add .
          git commit -m "chore(release): deps update"
          git push --set-upstream origin deps_update

          echo "👏  Go and open that PR now:"
          echo "🔗  $homepage/compare/master...deps_update"

          gh pr create --title "chore(release): deps_update" --fill
          echo "🎉 Done!"
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

